# Author : amousset <contact@amousset.me>
# Adapted from https://protesilaos.com/emacs/modus-themes, by Protesilaos Stavrou
# Version 4.2.0

inherits = "modus_operandi"

# key = { fg = "#ffffff",
#         bg = "#000000",
#         underline = { color = "#ff0000", style = "curl"},
#         modifiers = ["bold", "italic"] }

# Syntax highlighting
# -------------------
"type" = "cyan-cooler"

"constructor" = ""

"constant" = "blue-cooler"
"constant.character.escape" = "magenta"

"string" = "blue-warmer"
"string.regexp" = ""
"string.special" = ""

"comment" = "fg-dim"
"comment.block.documentation" = "green-faint"

"variable.parameter" = "cyan"

"label" = "" # used for lifetimes

#"punctuation.special" = ""

"keyword" = "magenta-cooler"
"keyword.directive" = "red-cooler"

"function" = "blue"

"tag" = "zz"
"attribute" = "zz"

"namespace" = { fg = "", modifiers = ["italic"] }

"special" = "red-cooler"

"markup.heading.marker" = { fg = "", modifiers = ["bold"] }
"markup.heading.1" = "fg-main"
"markup.heading.2" = "yellow-faint"
"markup.heading.3" = "fg-alt"
"markup.heading.4" = "magenta"
"markup.heading.5" = "green-faint"
"markup.heading.6" = "red-faint"
"markup.list" = ""
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue-warmer", modifiers = ["underlined"] }
"markup.link.text" = "blue-warmer"
"markup.raw" = ""

"diff.plus" = "bg-added"
"diff.minus" = "bg-removed"
"diff.delta" = "bg-changed"

# User Interface
# --------------
"ui.background" = { bg = "bg-main" }

"ui.linenr" = { fg = "fg-dim", bg = "bg-dim" }
"ui.linenr.selected" = { fg = "fg-main", bg = "bg-active" }

"ui.statusline" = { fg = "fg-mode-line-active", bg = "bg-mode-line-active" }
"ui.statusline.inactive" = { fg = "fg-mode-line-inactive", bg = "bg-mode-line-inactive" }

"ui.popup" = { fg = "fg-main", bg = "bg-dim" }
"ui.window" = { fg = "fg-dim" }
"ui.help" = { fg = "fg-main", bg = "bg-dim" }

"ui.gutter" = { bg = "bg-dim" }

#"ui.bufferline" = { fg = "fg-main", bg = "bg-main" }
#"ui.bufferline.active" = { fg = "", bg = "", underline = { color = "", style = "line" } }
#"ui.bufferline.background" = { bg = "zz" }

"ui.text" = "fg-main"
"ui.text.focus" = { fg = "fg-main", bg = "", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "fg-dim" }

"ui.virtual" = "zz"
"ui.virtual.ruler" = { bg = "bg-dim" }
"ui.virtual.indent-guide" = "zz"
"ui.virtual.inlay-hint" = { fg = "fg-dim", modifiers = ["italic"] }

"ui.selection" = { fg = "fg-main", bg = "bg-active" }

"ui.cursor" = { fg = "bg-main", bg = "fg-main" }
"ui.cursor.primary" = { fg = "", bg = "" }
"ui.cursor.match" = { bg = "bg-paren-match" }

"ui.cursor.primary.normal" = { fg = "bg-main", bg = "fg-main" }
"ui.cursor.primary.insert" = { fg = "", bg = "" }
"ui.cursor.primary.select" = { fg = "", bg = "" }

#"ui.cursor.normal" = { fg = "base", bg = "secondary_cursor_normal" }
#"ui.cursor.insert" = { fg = "base", bg = "secondary_cursor_insert" }
#"ui.cursor.select" = { fg = "base", bg = "secondary_cursor" }

"ui.cursorline.primary" = { bg = "bg-hl-line" }

"ui.highlight" = { bg = "", modifiers = ["bold"] }

"ui.menu" = { fg = "fg-dim", bg = "bg-dim" }
"ui.menu.selected" = { fg = "fg-dim", bg = "bg-completion", modifiers = ["bold"] }

#"diagnostic.hint" = { underline = { color = "silver", style = "curl" } }
"diagnostic.info" = { underline = { color = "cyan-intense", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow-intense", style = "curl" } }
"diagnostic.error" = { underline = { color = "red-intense", style = "curl" } }

warning = "yellow-warmer"
error = "red"
info = "cyan-cooler"
#hint = "silver"

[palette]
yellow = "#695500"
yellow-warmer = "#973300"
yellow-cooler = "#77492f"

# Special purpose
bg-mode-line-active = "#d0d6ff"
fg-mode-line-active = "#0f0f0f"
border-mode-line-active = "#4f4f4f"

modeline-err = "#603a00"
modeline-warning = "#454500"
modeline-info = "#023d92"

# Diffs
bg-added = "#d5d7ff"
bg-added-faint = "#e6e6ff"
bg-added-refine = "#babcef"
fg-added = "#303099"
fg-added-intense = "#0303cc"

bg-changed = "#eecfdf"
bg-changed-faint = "#f0dde5"
bg-changed-refine = "#e0b0d0"
fg-changed = "#6f1343"
fg-changed-intense = "#7f0f9f"

bg-removed = "#f4f099"
bg-removed-faint = "#f6f6b7"
bg-removed-refine = "#ede06f"
fg-removed = "#553d00"
fg-removed-intense = "#7f6f00"
